[settings]
timeout = 10000

[relaychain]
chain = "rococo-local"
default_command = "~/bin/polkadot"
default_args = ["-lparachain=debug"]

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
rpc_port = 9977
