[settings]
timeout = 10000

[relaychain]
chain = "rococo-local"
default_command = "~/bin/polkadot"
default_args = ["-lparachain=debug"]

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
rpc_port = 9977

[[parachains]]
id = 2267
addToGenesis = true
cumulus_based = true
chain = "shell-rococo-local-dev"

[[parachains.collators]]
name = "shell-collator01"
command = "./target/release/integritee-collator"
rpc_port = 9944

[[parachains.collators]]
name = "shell-collator02"
command = "./target/release/integritee-collator"
rpc_port = 9945
