[settings]
timeout = 10000

[relaychain]
chain = "rococo-local"
default_command = "~/bin/polkadot"
default_args = ["-lparachain=debug,xcm=trace"]

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
rpc_port = 9977

[[parachains]]
id = 2015
addToGenesis = true
cumulus_based = true
chain = "integritee-rococo-local-dev"

[[parachains.collators]]
name = "integritee-collator01"
#command = "~/bin/integritee-collator-v1.6.4"
command = "./target/release/integritee-collator"
args = ["-lxcm=trace,runtime=debug"]
rpc_port = 9944

[[parachains.collators]]
name = "integritee-collator02"
#command = "~/bin/integritee-collator-v1.6.4"
command = "./target/release/integritee-collator"
args = ["-lxcm=trace,runtime=debug"]
rpc_port = 9945

