[settings]
timeout = 10000

[relaychain]
chain = "rococo-local"
default_command = "~/code/bin/polkadot-v0.9.43"
default_args = [ "-lparachain=debug" ]

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9999

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9988

[[relaychain.nodes]]
name = "charlie"
validator = true
ws_port = 9977
