[package]
name = "parachains-common"
# major.minor revision must match collator node. patch bump ad lib
version = "1.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Logic which is common to all parachain runtimes"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# External dependencies
codec = { package = 'parity-scale-codec', version = '3.0.0', features = ['derive'], default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

# dependencies not existing upstream
smallvec = "1.6.1"

# Substrate dependencies
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
sp-std = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
sp-io = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
frame-executive = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
frame-system = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
pallet-assets = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
pallet-balances = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
sp-runtime = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
sp-core = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }

# Polkadot dependencies
polkadot-runtime-common = { git = 'https://github.com/paritytech/polkadot', default-features = false, branch = "release-v0.9.19" }
polkadot-primitives = { git = 'https://github.com/paritytech/polkadot', default-features = false, branch = "release-v0.9.19" }
polkadot-core-primitives = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.19" }
xcm = { git = 'https://github.com/paritytech/polkadot', default-features = false, branch = "release-v0.9.19" }
xcm-executor = { git = 'https://github.com/paritytech/polkadot', default-features = false, branch = "release-v0.9.19" }

[dev-dependencies]
sp-io = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }
pallet-authorship = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = "polkadot-v0.9.19" }

[build-dependencies]
substrate-wasm-builder = { git = 'https://github.com/paritytech/substrate', branch = "polkadot-v0.9.19" }

[features]
default = ["std"]
std = [
	'codec/std',
	'scale-info/std',
	'sp-consensus-aura/std',
	'sp-std/std',
	'sp-io/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'pallet-assets/std',
	'pallet-authorship/std',
	'pallet-balances/std',
	'polkadot-core-primitives/std',
	'polkadot-runtime-common/std',
	'polkadot-primitives/std',
]
