#!/bin/bash

# import common functions
source "$FRAMEWORK_PATH/utils/bridges.sh"

# Expected sovereign accounts.
#
# Generated by:
#
##[test]
#fn generate_sovereign_accounts() {
#	use polkadot_parachain_primitives::primitives::Sibling;
#	use sp_core::crypto::Ss58Codec;
#
#	parameter_types! {
#		pub UniversalLocationAHP: InteriorLocation = [GlobalConsensus(Polkadot), Parachain(1000)].into();
#		pub UniversalLocationAHK: InteriorLocation = [GlobalConsensus(Kusama), Parachain(1000)].into();
#	}
#
#
#	println!(
#		"GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			GlobalConsensusConvertsFor::<UniversalLocationAHK, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Polkadot)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(1000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#
#	println!(
#		"GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			GlobalConsensusConvertsFor::<UniversalLocationAHP, [u8; 32]>::convert_location(
#				&Location { parents: 2, interior: [GlobalConsensus(Kusama)].into() }
#			)
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#	println!(
#		"ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			SiblingParachainConvertsVia::<Sibling, [u8; 32]>::convert_location(&Location {
#				parents: 1,
#				interior: [Parachain(1000)].into()
#			})
#			.unwrap()
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#}
GLOBAL_CONSENSUS_POLKADOT_SOVEREIGN_ACCOUNT="FxqimVubBRPqJ8kTwb3wL7G4q645hEkBEnXPyttLsTrFc5Q"
ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA="FBeL7EFTDeHnuViqaUHUXvhhUusN5FawDmHgfvzF97DXFr3"
GLOBAL_CONSENSUS_KUSAMA_SOVEREIGN_ACCOUNT="14zcUAhP5XypiFQWA3b1AnGKrhZqR4XWUo4deWkwuN5y983G"
ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT="13cKp89SgdtqUngo2WiEijPrQWdHFhzYZLf2TJePKRvExk7o"
INTEGRITEE_KUSAMA_SIBLING_ACCOUNT="FBeL7EDeogX8JScLQqEVZJtvKRukqBTM8dwZWJvXUFoaiJP"
INTEGRITEE_POLKADOT_SIBLING_ACCOUNT="13cKp89Vh9FRH3u4ESYeNA7jxX3K78KMLJqPUgyonot6TFbF"
BOB_SOVEREIGN_ACCOUNT_AT_KUSAMA="FoQJpPyadYccjavVdTWxpxU7rUEaYhfLCPwXgkfD6Zat9QP"
BOB_SOVEREIGN_ACCOUNT_AT_POLKADOT="14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3"

# Expected sovereign accounts for rewards on BridgeHubs.
#
# Generated by:
##[test]
#fn generate_sovereign_accounts_for_rewards() {
#	use bp_messages::LaneId;
#	use bp_relayers::{PayRewardFromAccount, RewardsAccountOwner, RewardsAccountParams};
#	use sp_core::crypto::Ss58Codec;
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhks",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(0_u16.into())
#	);
#
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::ThisChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#
#	println!(
#		"ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain=\"{}\"",
#		frame_support::sp_runtime::AccountId32::new(
#			PayRewardFromAccount::<[u8; 32], [u8; 32]>::rewards_account(RewardsAccountParams::new(
#				LaneId([0, 0, 0, 1]),
#				*b"bhpd",
#				RewardsAccountOwner::BridgedChain
#			))
#		)
#		.to_ss58check_with_version(2_u16.into())
#	);
#}
ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain="13E5fui93Uyua5RtDv2LQj4aVBBHo6YREe3n6CBwYdqNqoxj"
ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain="13E5fui93Uyua5RtDv2c9kcAbfrVFeeHyJzHe8sn1Ti77Afd"
ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain="EoQBtnwp4jMtCEpV7C88rKrz6x1qMBh2z74ibGSqtZRnuMM"
ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain="EoQBtnwp4jMtCEpV7CPsssT6bdDHuHZmf3aGXxHJiSA4Dz3"

LANE_ID="00000001"
XCM_VERSION=5

AHK_DOT_ED=10000000
DOT=10000000000

AHP_KSM_ED=10000000
KSM=1000000000000

TEER_ED=1000000000
TEER=1000000000000

function init_polkadot_kusama() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge polkadot-to-bridge-hub-kusama \
	--source-uri ws://localhost:9942 \
	--source-version-mode Auto \
	--target-uri ws://localhost:8945 \
	--target-version-mode Auto \
	--target-signer //Alice
}

function init_kusama_polkadot() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path init-bridge kusama-to-bridge-hub-polkadot \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Alice
}

function run_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers-and-messages bridge-hub-kusama-bridge-hub-polkadot \
        --polkadot-uri ws://localhost:9942 \
        --polkadot-version-mode Auto \
        --bridge-hub-polkadot-uri ws://localhost:8943 \
        --bridge-hub-polkadot-version-mode Auto \
        --bridge-hub-polkadot-signer //Charlie \
        --bridge-hub-polkadot-transactions-mortality 4 \
        --kusama-uri ws://localhost:9945 \
        --kusama-version-mode Auto \
        --bridge-hub-kusama-uri ws://localhost:8945 \
        --bridge-hub-kusama-version-mode Auto \
        --bridge-hub-kusama-signer //Charlie \
        --bridge-hub-kusama-transactions-mortality 4 \
        --lane "${LANE_ID}"
}

function run_finality_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers polkadot-to-bridge-hub-kusama \
        --only-free-headers \
        --source-uri ws://localhost:9942 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Charlie \
        --target-transactions-mortality 4&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-headers kusama-to-bridge-hub-polkadot \
        --only-free-headers \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Charlie \
        --target-transactions-mortality 4
}

function run_parachains_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-parachains bridge-hub-polkadot-to-bridge-hub-kusama \
        --only-free-headers \
        --source-uri ws://localhost:9942 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Dave \
        --target-transactions-mortality 4&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-parachains bridge-hub-kusama-to-bridge-hub-polkadot \
        --only-free-headers \
        --source-uri ws://localhost:9945 \
        --source-version-mode Auto \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Dave \
        --target-transactions-mortality 4
}

function run_messages_relay() {
    local relayer_path=$(ensure_relayer)

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-messages bridge-hub-polkadot-to-bridge-hub-kusama \
        --source-uri ws://localhost:8943 \
        --source-version-mode Auto \
        --source-signer //Eve \
        --source-transactions-mortality 4 \
        --target-uri ws://localhost:8945 \
        --target-version-mode Auto \
        --target-signer //Eve \
        --target-transactions-mortality 4 \
        --lane $LANE_ID&

    RUST_LOG=runtime=trace,rpc=trace,bridge=trace \
        $relayer_path relay-messages bridge-hub-kusama-to-bridge-hub-polkadot \
        --source-uri ws://localhost:8945 \
        --source-version-mode Auto \
        --source-signer //Ferdie \
        --source-transactions-mortality 4 \
        --target-uri ws://localhost:8943 \
        --target-version-mode Auto \
        --target-signer //Ferdie \
        --target-transactions-mortality 4 \
        --lane $LANE_ID
}

case "$1" in
  run-relay)
      init_kusama_polkadot
      init_polkadot_kusama
      run_relay
      ;;
  run-finality-relay)
      init_kusama_polkadot
      init_polkadot_kusama
      run_finality_relay
      ;;
  run-parachains-relay)
      run_parachains_relay
      ;;
  run-messages-relay)
      run_messages_relay
      ;;
  init-polkadot-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 1002 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 1000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 2039 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          2039 1000 4 524288
      # governance set XCM version of remote AssetHubKusama on AHP
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      # governance set XCM version of remote BridgeHubKusama on BHP
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-asset-hub-polkadot-local)
      ensure_polkadot_js_api
      # create pool for DOT and wKSM
      create_pool \
          "ws://127.0.0.1:9910" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Kusama" }] } }')"
      # Create liquidity in the pool @ 10 DOT = 4 KSM
      add_liquidity \
          "ws://127.0.0.1:9910" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Kusama"}] } }')" \
          100000000000 \
          4000000000000 \
          "$BOB_SOVEREIGN_ACCOUNT_AT_POLKADOT"
      # create foreign assets for native Kusama token (governance call on Polkadot)
      force_create_foreign_asset \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 2039 } ] } }')" \
          "$INTEGRITEE_POLKADOT_SIBLING_ACCOUNT" \
          $TEER_ED \
          false
      # SA of sibling integritee pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$INTEGRITEE_POLKADOT_SIBLING_ACCOUNT" \
          $((25 * $DOT))
      # set XCM version of remote AssetHubKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-polkadot-local)
      ensure_polkadot_js_api
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT" \
          $((25 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_ThisChain" \
          $((25 * $DOT))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8943" \
          "//Alice" \
          "$ON_BRIDGE_HUB_POLKADOT_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhks_BridgedChain" \
          $((25 * $DOT))
      # set XCM version of remote BridgeHubKusama
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8943" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-kusama-local)
      ensure_polkadot_js_api
      # HRMP
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 1002 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 1000 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 2015 4 524288
      open_hrmp_channels \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          2015 1000 4 524288

      # governance set XCM version of remote AssetHubPolkadot on AHK
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      # governance set XCM version of remote BridgeHubPolkadot on BHK
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-asset-hub-kusama-local)
      ensure_polkadot_js_api
      # create pool for KSM and wDOT
      create_pool \
          "ws://127.0.0.1:9010" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Polkadot" }] } }')"
      # Create liquidity in the pool @ 1 KSM = 2.5 DOT.
      add_liquidity \
          "ws://127.0.0.1:9010" \
          "//Bob" \
          "$(jq --null-input '{ "parents": 1, "interior": "Here" }')" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X1": [{ "GlobalConsensus": "Polkadot"}] } }')" \
          1000000000000 \
          25000000000 \
          "$BOB_SOVEREIGN_ACCOUNT_AT_KUSAMA"
      force_create_foreign_asset \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 2015 } ] } }')" \
          "$INTEGRITEE_KUSAMA_SIBLING_ACCOUNT" \
          $TEER_ED \
          false
      # SA of sibling integritee pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$INTEGRITEE_KUSAMA_SIBLING_ACCOUNT" \
          $((25 * $KSM))
      # set XCM version of remote AssetHubPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1000 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } }')" \
          $XCM_VERSION
      ;;
  init-bridge-hub-kusama-local)
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA" \
          $((25 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_ThisChain" \
          $((25 * $KSM))
      # drip SA of lane dedicated to asset hub for paying rewards for delivery confirmation
      transfer_balance \
          "ws://127.0.0.1:8945" \
          "//Alice" \
          "$ON_BRIDGE_HUB_KUSAMA_SOVEREIGN_ACCOUNT_FOR_LANE_00000001_bhpd_BridgedChain" \
          $((25 * $KSM))
      # set XCM version of remote BridgeHubPolkadot
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          1002 \
          "ws://127.0.0.1:8945" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1002 } ] } }')" \
          $XCM_VERSION
      ;;
  init-integritee-kusama-local)
      # SA of sibling asset hub pays for the execution
      transfer_balance \
          "ws://127.0.0.1:9144" \
          "//Alice" \
          "$ASSET_HUB_KUSAMA_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_KUSAMA" \
          $((25 * $TEER))
      # root origin local account
      transfer_balance \
          "ws://127.0.0.1:9144" \
          "//Alice" \
          "2JZNyFtn2KWCcgU6vM7Mh7TXR2BGCdewgPxZCQaofwcbF5cn" \
          $((100 * $TEER))
      # sovereign account of IK on PAH
      transfer_balance \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "14DXRZEfzojXowgGnamfGzTjnMERF9cVWRkdHHYQFiTsDiXB" \
          $((100 * $DOT))
      # set XCM version of remote IntegriteePolkadot for relay and AH
      force_xcm_version \
          "ws://127.0.0.1:9945" \
          "//Alice" \
          2015 \
          "ws://127.0.0.1:9010" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 2039 } ] } }')" \
          $XCM_VERSION

      # above call has no authority over integritee. need to do it locally
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 2039 } ] } }')" \
              $XCM_VERSION
      # also for KAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } }')" \
              $XCM_VERSION
      echo "Creating asset for KSM token on IntegriteeKusama"
      # create sufficient asset for KSM token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.assets.forceCreate \
              "0" \
              "2L44Bkyt9uJDvu1HE71So8DiJcZxLzG6euhLBApX6TQK71kZ" \
              "true" \
              "$AHP_KSM_ED" \
      # force metadata KSM token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.assets.forceSetMetadata \
              "0" \
              "Kusama KSM" \
              "KSM" \
              "12" \
              "false" \
      # register location for KSM token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.registerReserveAsset \
              "0" \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
      # create a TEER/KSM pool on KAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9010" \
          --seed "//Alice" \
          tx.assetConversion.createPool \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2015 }]}}')" \
      # send 10 KSM to IK Alice for initial fees
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 2015 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '10000000000000' } } ] }')" \
          0 \
          "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on IK"
      sleep 30
      # send 100 TEER to KAH Alice for pool
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          tx.polkadotXcm.transferAssets \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } } }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
              "$(jq --null-input '{ "V4": [ { "id": { "parents": 0, "interior": "Here" }, "fun": { "Fungible": '100000000000000' } }, { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '100000000000' } } ] }')" \
              "1" \
              "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on KAH"
      sleep 30
      # provide liquidity to TEER/KSM pool on KAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9010" \
          --seed "//Alice" \
          tx.assetConversion.addLiquidity \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2015 }]}}')" \
              "1000000000000" \
              "90000000000000" \
              "1" \
              "1" \
              "HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F"
      # enable the TEER bridge on IK
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.setPorteerConfig \
              "$(jq --null-input '{ "sendEnabled": true, "receiveEnabled": true}')"
      # make Alice the watchdog
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.setWatchdog \
              "2P2pRoXYwZAWVPXXtR6is5o7L34Me72iuNdiMZxeNV2BkgsH"
      # whitelist KAH location on IK as direct forwarding location
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9144" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.addLocationToWhitelist \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 1000 }]}}')"
      ;;
  init-integritee-polkadot-local)
      # SA of sibling asset hub pays for the inwards execution
      transfer_balance \
          "ws://127.0.0.1:9244" \
          "//Alice" \
          "$ASSET_HUB_POLKADOT_SOVEREIGN_ACCOUNT_AT_BRIDGE_HUB_POLKADOT" \
          $((25 * $TEER))
      # root origin local account on IP
      transfer_balance \
          "ws://127.0.0.1:9244" \
          "//Alice" \
          "2JZNyFtn2KWCcgU6vM7Mh7TXR2BGCdewgPxZCQaofwcbF5cn" \
          $((100 * $TEER))
      # sovereign account of IP on KAH
      transfer_balance \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "J4jPjaphmo2vzeEWEKaXfB1u3W2VWxDTNwyFuSMvStoQb4F" \
          $((10 * $KSM))
      # set XCM version of remote IntegriteeKusama for relay and AH
      force_xcm_version \
          "ws://127.0.0.1:9942" \
          "//Alice" \
          2039 \
          "ws://127.0.0.1:9910" \
          "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 2015 } ] } }')" \
          $XCM_VERSION

      # above call has no authority over integritee. need to do it locally
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 2015 } ] } }')" \
              $XCM_VERSION
      # also for PAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.polkadotXcm.forceXcmVersion \
              "$(jq --null-input '{ "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } }')" \
              $XCM_VERSION
      echo "Creating asset for DOT token on IntegriteePolkadot"
      # create sufficient asset for DOT token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.assets.forceCreate \
              "0" \
              "2Li4fsP2bHBbSwpa2rgaswP22Kpqpr4uLyzbuym2Kc82v6oG" \
              "true" \
              "$AHK_DOT_ED" \
      # force metadata DOT token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.assets.forceSetMetadata \
              "0" \
              "Polkadot DOT" \
              "DOT" \
              "10" \
              "false" \
      # register location for DOT token
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.assetRegistry.registerReserveAsset \
              "0" \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
      # create a TEER/DOT pool on PAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9910" \
          --seed "//Alice" \
          tx.assetConversion.createPool \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2039 }]}}')" \
      # send 10 DOT to IP Alice for initial fees
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 2039 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '100000000000' } } ] }')" \
          0 \
          "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on IP"
      sleep 30
      # send 100 TEER to PAH Alice for pool
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          tx.polkadotXcm.transferAssets \
              "$(jq --null-input '{ "V4": { "parents": 1, "interior": { "X1": [ { "Parachain": 1000 } ] } } }')" \
              "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
              "$(jq --null-input '{ "V4": [ { "id": { "parents": 0, "interior": "Here" }, "fun": { "Fungible": '100000000000000' } }, { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '100000000000' } } ] }')" \
              "1" \
              "Unlimited"
      # here we need to wait until funds arrive, not only until inBlock
      echo "Waiting for funds to arrive on PAH"
      sleep 30
      # provide liquidity to TEER/DOT pool on PAH
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9910" \
          --seed "//Alice" \
          tx.assetConversion.addLiquidity \
              "$(jq --null-input '{ "parents": 1, "interior": "Here"}')" \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 2039 }]}}')" \
              "40000000000" \
              "90000000000000" \
              "1" \
              "1" \
              "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5"
      # enable the TEER bridge on IP
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.setPorteerConfig \
              "$(jq --null-input '{ "sendEnabled": true, "receiveEnabled": true}')"
      # make Alice the watchdog
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.setWatchdog \
              "2P2pRoXYwZAWVPXXtR6is5o7L34Me72iuNdiMZxeNV2BkgsH"
      # whitelist KAH location on IK as direct forwarding location
      call_polkadot_js_api \
          --ws "ws://127.0.0.1:9244" \
          --seed "//Alice" \
          --sudo \
          tx.porteer.addLocationToWhitelist \
              "$(jq --null-input '{ "parents": 1, "interior": { "x1": [{ "parachain": 1000 }]}}')"
      ;;
  reserve-transfer-assets-from-asset-hub-polkadot-local)
      amount=$2
      ensure_polkadot_js_api
      # send DOTs to Alice account on AHK
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  withdraw-reserve-assets-from-asset-hub-polkadot-local)
      amount=$2
      ensure_polkadot_js_api
      # send back some wrappedKSMs to Alice account on AHK
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9910" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Kusama" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 2, "interior": { "X1": [ { "GlobalConsensus": "Kusama" } ] } }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  reserve-transfer-assets-from-asset-hub-kusama-local)
      amount=$2
      ensure_polkadot_js_api
      # send KSMs to Alice account on AHP
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 1, "interior": "Here" }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  withdraw-reserve-assets-from-asset-hub-kusama-local)
      amount=$2
      ensure_polkadot_js_api
      # send back some wrappedDOTs to Alice account on AHP
      limited_reserve_transfer_assets \
          "ws://127.0.0.1:9010" \
          "//Alice" \
          "$(jq --null-input '{ "V4": { "parents": 2, "interior": { "X2": [ { "GlobalConsensus": "Polkadot" }, { "Parachain": 1000 } ] } } }')" \
          "$(jq --null-input '{ "V4": { "parents": 0, "interior": { "X1": [ { "AccountId32": { "id": [212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125] } } ] } } }')" \
          "$(jq --null-input '{ "V4": [ { "id": { "parents": 2, "interior": { "X1": [ { "GlobalConsensus": "Polkadot" } ] } }, "fun": { "Fungible": '$amount' } } ] }')" \
          0 \
          "Unlimited"
      ;;
  *)
      echo "A command is require. Supported commands for:
      Local (zombienet) run:
            - run-relay
            - run-finality-relay
            - run-parachains-relay
            - run-messages-relay
            - init-asset-hub-polkadot-local
            - init-bridge-hub-polkadot-local
            - init-asset-hub-kusama-local
            - init-bridge-hub-kusama-local
            - reserve-transfer-assets-from-asset-hub-polkadot-local
            - withdraw-reserve-assets-from-asset-hub-polkadot-local
            - reserve-transfer-assets-from-asset-hub-kusama-local
            - withdraw-reserve-assets-from-asset-hub-kusama-local";
      exit 1
      ;;
esac
