
//! Autogenerated weights for `pallet_teeracle`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 39.0.0
//! DATE: 2024-08-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `caribe`, CPU: `12th Gen Intel(R) Core(TM) i7-1260P`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("integritee-rococo-local-dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/integritee-collator
// benchmark
// pallet
// --chain=integritee-rococo-local-dev
// --steps=50
// --repeat=20
// --pallet=pallet_teeracle
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./polkadot-parachains/integritee-runtime/src/weights/pallet_teeracle.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_teeracle`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_teeracle::WeightInfo for WeightInfo<T> {
	/// Storage: `Teerex::SovereignEnclaves` (r:1 w:0)
	/// Proof: `Teerex::SovereignEnclaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teeracle::Whitelists` (r:1 w:0)
	/// Proof: `Teeracle::Whitelists` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teeracle::ExchangeRates` (r:1 w:1)
	/// Proof: `Teeracle::ExchangeRates` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_exchange_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `529`
		//  Estimated: `3994`
		// Minimum execution time: 24_383_000 picoseconds.
		Weight::from_parts(25_910_000, 0)
			.saturating_add(Weight::from_parts(0, 3994))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Teerex::SovereignEnclaves` (r:1 w:0)
	/// Proof: `Teerex::SovereignEnclaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teeracle::Whitelists` (r:1 w:0)
	/// Proof: `Teeracle::Whitelists` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Teeracle::OracleData` (r:0 w:1)
	/// Proof: `Teeracle::OracleData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_oracle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `520`
		//  Estimated: `3985`
		// Minimum execution time: 19_831_000 picoseconds.
		Weight::from_parts(21_082_000, 0)
			.saturating_add(Weight::from_parts(0, 3985))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Teeracle::Whitelists` (r:1 w:1)
	/// Proof: `Teeracle::Whitelists` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_to_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `3545`
		// Minimum execution time: 10_146_000 picoseconds.
		Weight::from_parts(10_739_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Teeracle::Whitelists` (r:1 w:1)
	/// Proof: `Teeracle::Whitelists` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_from_whitelist() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3647`
		// Minimum execution time: 13_021_000 picoseconds.
		Weight::from_parts(13_675_000, 0)
			.saturating_add(Weight::from_parts(0, 3647))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
